image: python:3.6-alpine

stages:
  - test
  - coverage

test_with_pytest:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest --cov=src --cov-report=xml tests/unit
  artifacts:
    paths:
      - coverage.xml

coverage_with_codecov:
  stage: coverage
  script:
    - pip install codecov 
    - codecov -t 1a627f4d-9dda-4ff1-b596-ebfe058373a3